package streaming

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"github.com/rs/zerolog"
)

type FfmpegTranscoder struct {
	FfmpegPath string
	OutDir     string
	logger     *zerolog.Logger
}

func NewTranscoder(ffmpegPath string, logger *zerolog.Logger) *FfmpegTranscoder {
	if ffmpegPath == "" {
		ffmpegPath = "ffmpeg"
	}
	outDir := "/tmp/kamehouse_transcodes"
	// Ensure temp directory exists
	_ = os.MkdirAll(outDir, 0755)

	return &FfmpegTranscoder{
		FfmpegPath: ffmpegPath,
		OutDir:     outDir,
		logger:     logger,
	}
}

// StartSession initiates an async ffmpeg process producing HLS
func (t *FfmpegTranscoder) StartSession(ctx context.Context, mediaId string, inputFile string) (string, error) {
	sessionDir := filepath.Join(t.OutDir, mediaId)
	_ = os.MkdirAll(sessionDir, 0755)

	masterPlaylist := filepath.Join(sessionDir, "master.m3u8")

	// Avoid restarting if it's already there (naive check)
	if _, err := os.Stat(masterPlaylist); err == nil {
		t.logger.Info().Str("mediaId", mediaId).Msg("streaming: Transcode session already exists")
		return masterPlaylist, nil
	}

	// -c:v libx264 -preset veryfast -hls_time 3
	args := []string{
		"-y", // overwrite
		"-i", inputFile,
		"-c:v", "libx264",
		"-preset", "veryfast",
		"-c:a", "aac",
		"-f", "hls",
		"-hls_time", "3",
		"-hls_list_size", "0",
		"-hls_segment_filename", filepath.Join(sessionDir, "segment_%03d.ts"),
		masterPlaylist,
	}

	cmd := exec.CommandContext(ctx, t.FfmpegPath, args...)

	// Start async
	if err := cmd.Start(); err != nil {
		t.logger.Error().Err(err).Msg("streaming: Failed to start ffmpeg")
		return "", fmt.Errorf("ffmpeg start failed: %w", err)
	}

	// We let it run asynchronously attached to the Context. The caller must keep the Context alive.
	go func() {
		err := cmd.Wait()
		if err != nil {
			t.logger.Warn().Err(err).Msg("streaming: FFmpeg process exited or was killed")
		} else {
			t.logger.Info().Str("mediaId", mediaId).Msg("streaming: FFmpeg transcoding completed")
		}
	}()

	// Wait exactly 1-2 seconds to let the generic `master.m3u8` be generated by ffmpeg
	time.Sleep(2 * time.Second)

	return masterPlaylist, nil
}
