run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true

  enable:
    - exhaustruct
    - errcheck   # ensure errors are checked
    - govet      # go vet: correctness
    - ineffassign # detect ineffectual assignments
    - staticcheck # static analysis checks
    - gosec      # security checks
    - nilerr     # check for returning nil error
    - bodyclose  # check whether HTTP response body is closed
    - contextcheck # check whether context is passed correctly
