/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as SeriesSeriesIdIndexRouteImport } from './routes/series/$seriesId/index'
import { Route as SeriesSeriesIdSagaIdRouteImport } from './routes/series/$seriesId/$sagaId'

const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdIndexRoute = SeriesSeriesIdIndexRouteImport.update({
  id: '/series/$seriesId/',
  path: '/series/$seriesId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdSagaIdRoute = SeriesSeriesIdSagaIdRouteImport.update({
  id: '/series/$seriesId/$sagaId',
  path: '/series/$seriesId/$sagaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/home/': typeof HomeIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/series/$seriesId/$sagaId': typeof SeriesSeriesIdSagaIdRoute
  '/series/$seriesId/': typeof SeriesSeriesIdIndexRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/series': typeof SeriesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/series/$seriesId/$sagaId': typeof SeriesSeriesIdSagaIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home/': typeof HomeIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/series/$seriesId/$sagaId': typeof SeriesSeriesIdSagaIdRoute
  '/series/$seriesId/': typeof SeriesSeriesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home/'
    | '/movies/'
    | '/series/'
    | '/settings/'
    | '/series/$seriesId/$sagaId'
    | '/series/$seriesId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/movies'
    | '/series'
    | '/settings'
    | '/series/$seriesId/$sagaId'
    | '/series/$seriesId'
  id:
    | '__root__'
    | '/home/'
    | '/movies/'
    | '/series/'
    | '/settings/'
    | '/series/$seriesId/$sagaId'
    | '/series/$seriesId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SeriesSeriesIdSagaIdRoute: typeof SeriesSeriesIdSagaIdRoute
  SeriesSeriesIdIndexRoute: typeof SeriesSeriesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId/': {
      id: '/series/$seriesId/'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId/'
      preLoaderRoute: typeof SeriesSeriesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId/$sagaId': {
      id: '/series/$seriesId/$sagaId'
      path: '/series/$seriesId/$sagaId'
      fullPath: '/series/$seriesId/$sagaId'
      preLoaderRoute: typeof SeriesSeriesIdSagaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SeriesSeriesIdSagaIdRoute: SeriesSeriesIdSagaIdRoute,
  SeriesSeriesIdIndexRoute: SeriesSeriesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
