import { GettingStarted_Variables } from "@/api/generated/endpoint.types"
import type { Models_Settings } from "@/api/generated/types"
import { z } from "zod"



const _gettingStartedSchema = z.object({
    enableTranscode: z.boolean().optional().default(false),
    debridProvider: z.string().optional().default("none"),
    debridApiKey: z.string().optional().default(""),
})

export const settingsSchema = z.object({
    library: z.object({
        seriesPaths: z.array(z.string()).nullish().transform(v => v ?? []),
        moviePaths: z.array(z.string()).nullish().transform(v => v ?? []),
        autoScan: z.boolean().default(false),
        refreshLibraryOnStart: z.boolean().default(false),
        autoPlayNextEpisode: z.boolean().default(true),
        autoDetectSkipTimes: z.boolean().default(true),
        enableWatchContinuity: z.boolean().default(false),
        scannerMatchingThreshold: z.number().default(0),
        tmdbApiKey: z.string().default(""),
        tmdbLanguage: z.string().default("es-MX"),
        scannerUseLegacyMatching: z.boolean().default(false),
        scannerStrictStructure: z.boolean().default(false),
        scannerProvider: z.string().default("anilist"),
        disableLocalScanning: z.boolean().default(false),
        primaryMetadataProvider: z.string().default("anilist"),
        scannerConfig: z.string().optional().default(""),
        useFallbackMetadataProvider: z.boolean().optional().default(false),
        openWebURLOnStart: z.boolean().optional().default(false),
        lastScanAt: z.any().optional(),
        preferredAudioProfile: z.enum(["latino", "castellano", "japanese", "english", "auto"]).default("latino"),
        autoSkipIntro: z.boolean().default(false),
        autoSkipOutro: z.boolean().default(false),
        autoSkipFiller: z.boolean().default(false),
        autoDisableSubtitlesWhenDubbed: z.boolean().default(true),
        marathonMode: z.boolean().default(false),
        tvMode: z.boolean().default(false),
    }).passthrough().default({}),
    mediaPlayer: z.object({}).passthrough().default({}),
    mediastream: z.object({
        transcodeEnabled: z.boolean().default(false),
        transcodeHwAccel: z.string().default("auto"),
        transcodeThreads: z.number().default(0),
        transcodePreset: z.string().default("fast"),
        disableAutoSwitchToDirectPlay: z.boolean().default(false),
        directPlayOnly: z.boolean().default(false),
        preTranscodeEnabled: z.boolean().default(false),
        preTranscodeLibraryDir: z.string().default(""),
        transcodeHwAccelCustomSettings: z.string().default(""),
        ffmpegPath: z.string().default(""),
        ffprobePath: z.string().default(""),
        transcodeFfmpegPath: z.string().optional().default(""),
        transcodeFfprobePath: z.string().optional().default(""),
        performanceProfile: z.enum(["auto", "ultra", "balanced", "eco"]).default("auto"),
        autoGovernorEnabled: z.boolean().default(true),
    }).passthrough().default({}),
    theme: z.object({
        enableColorSettings: z.boolean().default(false),
        backgroundColor: z.string().default("#050506"),
        accentColor: z.string().default("#C8102E"),
        themeEra: z.string().default(""),
        themeMode: z.string().default(""),
        themeEnableLiquidGlass: z.boolean().default(false),
        themeSmallerEpisodeCarouselSize: z.boolean().default(false),
        themeExpandSidebarOnHover: z.boolean().default(false),
        themeLibraryScreenBannerType: z.string().default("dynamic"),
        themeLibraryScreenCustomBannerImage: z.string().default(""),
        themeLibraryScreenCustomBannerPosition: z.string().default("50% 50%"),
        themeLibraryScreenCustomBannerOpacity: z.number().default(10),
        themeLibraryScreenCustomBackgroundImage: z.string().default(""),
        themeLibraryScreenCustomBackgroundOpacity: z.number().default(10),
        themeLibraryScreenCustomBackgroundBlur: z.string().default("none"),
        themeEnableMediaPageBlurredBackground: z.boolean().default(false),
        themeDisableSidebarTransparency: z.boolean().default(false),
        themeDisableLibraryScreenGenreSelector: z.boolean().default(false),
        themeDisableCarouselAutoScroll: z.boolean().default(false),
        themeMediaPageBannerType: z.string().default("default"),
        themeMediaPageBannerSize: z.string().default("default"),
        themeMediaPageBannerInfoBoxSize: z.string().default("default"),
        themeShowEpisodeCardAnimeInfo: z.boolean().default(true),
        themeAnimeLibraryCollectionDefaultSorting: z.string().default("TITLE_ASC"),
        themeShowAnimeUnwatchedCount: z.boolean().default(true),
        themeHideEpisodeCardDescription: z.boolean().default(false),
        themeHideDownloadedEpisodeCardFilename: z.boolean().default(false),
        themeCustomCSS: z.string().max(20000).default(""),
        themeMobileCustomCSS: z.string().max(20000).default(""),
        themeUnpinnedMenuItems: z.array(z.string()).nullish().transform(v => v ?? []),
        themeEnableSidebarGradient: z.boolean().default(false),
        themeEnableBlurringEffects: z.boolean().default(true),
        themeEnableCinematicGrain: z.boolean().default(false),
        bgMusicEnabled: z.boolean().default(true),
        bgMusicVolume: z.number().min(0).max(1).default(0.25),
        bgMusicDir: z.string().default(""),
        bgMusicTracks: z.array(z.object({ name: z.string(), file: z.string() })).default([]),
        seriesSoundtrackMode: z.boolean().default(true),
        uiSoundsEnabled: z.boolean().default(true),
        uiSoundsVolume: z.number().min(0).max(1).default(1.0),
    }).passthrough().default({}),
    notifications: z.object({
        disableNotifications: z.boolean().default(false),
        disableAutoScannerNotifications: z.boolean().default(false),
    }).passthrough().default({}),
    Platform: z.object({
        hideAudienceScore: z.boolean().default(false),
    }).passthrough().default({}),
}).passthrough()

export const gettingStartedSchema = _gettingStartedSchema.extend({
    library: settingsSchema.shape.library,
    mediaPlayer: settingsSchema.shape.mediaPlayer,
    notifications: settingsSchema.shape.notifications.optional(),
})

export const getDefaultSettings = (data: z.infer<typeof gettingStartedSchema>, existingSettings?: Models_Settings | null): GettingStarted_Variables => ({
    library: {
        autoScan: data.library.autoScan ?? existingSettings?.library?.autoScan ?? false,
        refreshLibraryOnStart: existingSettings?.library?.refreshLibraryOnStart ?? false,
        autoPlayNextEpisode: data.library.autoPlayNextEpisode ?? existingSettings?.library?.autoPlayNextEpisode ?? true,
        autoDetectSkipTimes: data.library.autoDetectSkipTimes ?? existingSettings?.library?.autoDetectSkipTimes ?? true,
        enableWatchContinuity: data.library.enableWatchContinuity ?? existingSettings?.library?.enableWatchContinuity ?? true,
        seriesPaths: data.library.seriesPaths ?? existingSettings?.library?.seriesPaths ?? [],
        moviePaths: data.library.moviePaths ?? existingSettings?.library?.moviePaths ?? [],
        scannerMatchingThreshold: existingSettings?.library?.scannerMatchingThreshold ?? 0,
        scannerUseLegacyMatching: existingSettings?.library?.scannerUseLegacyMatching ?? false,
        scannerStrictStructure: existingSettings?.library?.scannerStrictStructure ?? false,
        scannerProvider: data.library.scannerProvider || existingSettings?.library?.scannerProvider || "anilist",
        disableLocalScanning: data.library.disableLocalScanning ?? existingSettings?.library?.disableLocalScanning ?? false,
        tmdbApiKey: data.library.tmdbApiKey || existingSettings?.library?.tmdbApiKey || "",
        tmdbLanguage: existingSettings?.library?.tmdbLanguage || "es-MX",
        primaryMetadataProvider: data.library.primaryMetadataProvider || existingSettings?.library?.primaryMetadataProvider || "anilist",
        preferredAudioProfile: (data.library as any).preferredAudioProfile ?? (existingSettings?.library as any)?.preferredAudioProfile ?? "latino",
        autoSkipIntro: (data.library as any).autoSkipIntro ?? (existingSettings?.library as any)?.autoSkipIntro ?? false,
        autoSkipOutro: (data.library as any).autoSkipOutro ?? (existingSettings?.library as any)?.autoSkipOutro ?? false,
        autoSkipFiller: (data.library as any).autoSkipFiller ?? (existingSettings?.library as any)?.autoSkipFiller ?? false,
        autoDisableSubtitlesWhenDubbed: (data.library as any).autoDisableSubtitlesWhenDubbed ?? (existingSettings?.library as any)?.autoDisableSubtitlesWhenDubbed ?? true,
        marathonMode: (data.library as any).marathonMode ?? (existingSettings?.library as any)?.marathonMode ?? false,
        tvMode: (data.library as any).tvMode ?? (existingSettings?.library as any)?.tvMode ?? false,
    } as any,
    mediaPlayer: existingSettings?.mediaPlayer || {},
    enableTranscode: data.enableTranscode ?? existingSettings?.mediastream?.transcodeEnabled ?? false,
})


