// Code generated by scripts/generate-sagas.ts — DO NOT EDIT.

export const DRAGON_BALL_SERIES = {
    ORIGINAL: 12609,
    Z: 12971,
    GT: 12697,
    KAI: 61709,
    KAI_FINAL_CHAPTERS: 42705,
    SUPER: 62715,
    DAIMA: 236994,
};

export type SubSagaDefinition = {
    id: string
    title: string
    description?: string
    startEp: number
    endEp: number
    iconicEp?: number
    image?: string
};

export type SagaDefinition = {
    id: string
    title: string
    description: string
    startEp: number
    endEp: number
    iconicEp?: number
    image?: string
    subSagas?: SubSagaDefinition[]
};

export const DRAGON_BALL_SAGAS: Record<number, SagaDefinition[]> = {
    [DRAGON_BALL_SERIES.ORIGINAL]: [
        {
            id: "pilaf",
            title: "Saga del Emperador Pilaf",
            description: "Saga del Emperador Pilaf saga",
            startEp: 1,
            endEp: 13,
            subSagas: [
                { id: "busqueda-esferas", title: "En busca de las Esferas del Dragón", description: "En busca de las Esferas del Dragón arc", startEp: 1, endEp: 7 },
                { id: "pilaf-castillo", title: "El Castillo del Emperador Pilaf", description: "El Castillo del Emperador Pilaf arc", startEp: 8, endEp: 13 },
            ],
        },
        {
            id: "torneo-21",
            title: "21º Torneo de Artes Marciales",
            description: "21º Torneo de Artes Marciales saga",
            startEp: 14,
            endEp: 28,
            subSagas: [
                { id: "entrenamiento-roshi", title: "Entrenamiento con el Maestro Roshi", description: "Entrenamiento con el Maestro Roshi arc", startEp: 14, endEp: 20 },
                { id: "torneo-21-combates", title: "El 21° Torneo", description: "El 21° Torneo arc", startEp: 21, endEp: 28 },
            ],
        },
        {
            id: "red-ribbon",
            title: "Saga de la Patrulla Roja",
            description: "Saga de la Patrulla Roja saga",
            startEp: 29,
            endEp: 68,
            subSagas: [
                { id: "coronel-silver", title: "Coronel Silver y los primeros enfrentamientos", description: "Coronel Silver y los primeros enfrentamientos arc", startEp: 29, endEp: 33 },
                { id: "torre-fuerza", title: "La Torre de la Fuerza — General White", description: "La Torre de la Fuerza — General White arc", startEp: 34, endEp: 45 },
                { id: "general-blue", title: "Aventura Submarina — General Blue", description: "Aventura Submarina — General Blue arc", startEp: 46, endEp: 57 },
                { id: "tao-pai-pai", title: "El Asesino Tao Pai Pai y la Torre Karin", description: "El Asesino Tao Pai Pai y la Torre Karin arc", startEp: 58, endEp: 68 },
            ],
        },
        {
            id: "uranai-baba",
            title: "Saga de Uranai Baba",
            description: "Saga de Uranai Baba saga",
            startEp: 69,
            endEp: 82,
            subSagas: [
                { id: "cinco-guerreros", title: "Los Cinco Guerreros de Uranai Baba", description: "Los Cinco Guerreros de Uranai Baba arc", startEp: 69, endEp: 76 },
                { id: "reencuentro-gohan", title: "El Reencuentro con el Abuelo Gohan", description: "El Reencuentro con el Abuelo Gohan arc", startEp: 77, endEp: 82 },
            ],
        },
        {
            id: "torneo-22",
            title: "22º Torneo de Artes Marciales",
            description: "22º Torneo de Artes Marciales saga",
            startEp: 83,
            endEp: 101,
            subSagas: [
                { id: "preparacion-22", title: "Preparación para el 22° Torneo", description: "Preparación para el 22° Torneo arc", startEp: 83, endEp: 85 },
                { id: "combates-22", title: "El 22° Torneo — Goku vs Tenshinhan", description: "El 22° Torneo — Goku vs Tenshinhan arc", startEp: 86, endEp: 101 },
            ],
        },
        {
            id: "piccolo-daimaku",
            title: "Saga del Rey Demonio Piccolo",
            description: "Saga del Rey Demonio Piccolo saga",
            startEp: 102,
            endEp: 122,
            subSagas: [
                { id: "liberacion-piccolo", title: "Liberación del Rey Demonio", description: "Liberación del Rey Demonio arc", startEp: 102, endEp: 111 },
                { id: "batalla-piccolo", title: "La Batalla Final contra el Rey Demonio", description: "La Batalla Final contra el Rey Demonio arc", startEp: 112, endEp: 122 },
            ],
        },
        {
            id: "piccolo-jr",
            title: "Saga de Piccolo Jr.",
            description: "Saga de Piccolo Jr. saga",
            startEp: 123,
            endEp: 153,
            subSagas: [
                { id: "preliminares-23", title: "Preliminares del 23° Torneo", description: "Preliminares del 23° Torneo arc", startEp: 123, endEp: 133 },
                { id: "goku-vs-piccolo-jr", title: "La Final: Goku vs Piccolo Jr.", description: "La Final: Goku vs Piccolo Jr. arc", startEp: 134, endEp: 153 },
            ],
        },
    ],
    [DRAGON_BALL_SERIES.Z]: [
        {
            id: "saiyajin",
            title: "Saga de los Saiyajin",
            description: "Saga de los Saiyajin saga",
            startEp: 1,
            endEp: 35,
            subSagas: [
                { id: "raditz", title: "La Llegada de Raditz", description: "La Llegada de Raditz arc", startEp: 1, endEp: 6 },
                { id: "entrenamiento-z", title: "Entrenamiento Especial", description: "Entrenamiento Especial arc", startEp: 7, endEp: 20 },
                { id: "vegeta-nappa", title: "Batalla contra Nappa y Vegeta", description: "Batalla contra Nappa y Vegeta arc", startEp: 21, endEp: 35 },
            ],
        },
        {
            id: "namek-freezer",
            title: "Saga Namek y Freezer",
            description: "Saga Namek y Freezer saga",
            startEp: 36,
            endEp: 107,
            subSagas: [
                { id: "viaje-namek", title: "Viaje a Namek", description: "Viaje a Namek arc", startEp: 36, endEp: 67 },
                { id: "fuerzas-ginyu", title: "Las Fuerzas Especiales Ginyu", description: "Las Fuerzas Especiales Ginyu arc", startEp: 68, endEp: 74 },
                { id: "goku-llega-namek", title: "Goku Llega a Namek", description: "Goku Llega a Namek arc", startEp: 75, endEp: 82 },
                { id: "cuatro-formas-freezer", title: "Las Cuatro Transformaciones de Freezer", description: "Las Cuatro Transformaciones de Freezer arc", startEp: 83, endEp: 97 },
                { id: "ssj-explosion-namek", title: "Nace el Super Saiyajin — Namek en Llamas", description: "Nace el Super Saiyajin — Namek en Llamas arc", startEp: 98, endEp: 107 },
            ],
        },
        {
            id: "garlic-jr",
            title: "Saga de Garlic Jr. (Relleno)",
            description: "Saga de Garlic Jr. (Relleno) saga",
            startEp: 108,
            endEp: 117,
        },
        {
            id: "androides",
            title: "Saga de los Androides",
            description: "Saga de los Androides saga",
            startEp: 118,
            endEp: 139,
            subSagas: [
                { id: "trunks-futuro", title: "Trunks del Futuro y la Advertencia", description: "Trunks del Futuro y la Advertencia arc", startEp: 118, endEp: 125 },
                { id: "androides-17-18", title: "Los Androides 17, 18 y 16", description: "Los Androides 17, 18 y 16 arc", startEp: 126, endEp: 139 },
            ],
        },
        {
            id: "cell",
            title: "Saga de Cell",
            description: "Saga de Cell saga",
            startEp: 140,
            endEp: 194,
            subSagas: [
                { id: "cell-imperfecto", title: "Cell Imperfecto", description: "Cell Imperfecto arc", startEp: 140, endEp: 152 },
                { id: "cell-semiperfecto", title: "Cell Semiperfecto", description: "Cell Semiperfecto arc", startEp: 153, endEp: 165 },
                { id: "juegos-cell", title: "Los Juegos de Cell", description: "Los Juegos de Cell arc", startEp: 166, endEp: 194 },
            ],
        },
        {
            id: "torneo-otro-mundo",
            title: "Saga del Torneo del Otro Mundo (Relleno)",
            description: "Saga del Torneo del Otro Mundo (Relleno) saga",
            startEp: 195,
            endEp: 199,
        },
        {
            id: "majin-buu",
            title: "Saga de Majin Buu",
            description: "Saga de Majin Buu saga",
            startEp: 200,
            endEp: 291,
            subSagas: [
                { id: "gran-saiyaman-arc", title: "El Gran Saiyaman", description: "El Gran Saiyaman arc", startEp: 200, endEp: 209 },
                { id: "torneo-25", title: "El 25° Torneo de Artes Marciales", description: "El 25° Torneo de Artes Marciales arc", startEp: 210, endEp: 219 },
                { id: "babidi-dabura-vegeta-majin", title: "La Nave de Babidi y Majin Vegeta", description: "La Nave de Babidi y Majin Vegeta arc", startEp: 220, endEp: 231 },
                { id: "despertar-buu-sacrificio-vegeta", title: "El Despertar de Buu y el Sacrificio de Vegeta", description: "El Despertar de Buu y el Sacrificio de Vegeta arc", startEp: 232, endEp: 237 },
                { id: "ssj3-fusion-dance", title: "El Super Saiyajin 3 y la Fusión", description: "El Super Saiyajin 3 y la Fusión arc", startEp: 238, endEp: 253 },
                { id: "super-buu", title: "La Amenaza de Super Buu", description: "La Amenaza de Super Buu arc", startEp: 254, endEp: 275 },
                { id: "fusion-kid-buu", title: "Fusión y Batalla Final contra Kid Buu", description: "Fusión y Batalla Final contra Kid Buu arc", startEp: 276, endEp: 287 },
                { id: "mundo-paz", title: "Un Mundo en Paz (Epílogo)", description: "Un Mundo en Paz (Epílogo) arc", startEp: 288, endEp: 291 },
            ],
        },
    ],
    [DRAGON_BALL_SERIES.GT]: [
        {
            id: "black-star",
            title: "Saga de las Esferas del Dragón Definitivas",
            description: "Saga de las Esferas del Dragón Definitivas saga",
            startEp: 1,
            endEp: 16,
            subSagas: [
                { id: "deseo-pilaf", title: "El Deseo de Pilaf y la Transformación", description: "El Deseo de Pilaf y la Transformación arc", startEp: 1, endEp: 3 },
                { id: "viaje-galaxia", title: "Viaje por la Galaxia", description: "Viaje por la Galaxia arc", startEp: 4, endEp: 16 },
            ],
        },
        {
            id: "baby",
            title: "Saga de Baby",
            description: "Saga de Baby saga",
            startEp: 17,
            endEp: 40,
            subSagas: [
                { id: "invasion-baby", title: "La Invasión de Baby", description: "La Invasión de Baby arc", startEp: 17, endEp: 27 },
                { id: "ssj4-baby", title: "Super Saiyajin 4 vs Baby", description: "Super Saiyajin 4 vs Baby arc", startEp: 28, endEp: 40 },
            ],
        },
        {
            id: "super-17",
            title: "Saga de Super-17",
            description: "Saga de Super-17 saga",
            startEp: 41,
            endEp: 47,
            subSagas: [
                { id: "portal-infierno", title: "El Portal del Infierno y los Regresos", description: "El Portal del Infierno y los Regresos arc", startEp: 41, endEp: 43 },
                { id: "super-17-batalla", title: "La Batalla contra Super 17", description: "La Batalla contra Super 17 arc", startEp: 44, endEp: 47 },
            ],
        },
        {
            id: "shadow-dragons",
            title: "Saga de los Dragones Malignos",
            description: "Saga de los Dragones Malignos saga",
            startEp: 48,
            endEp: 64,
            subSagas: [
                { id: "dragones-2-6", title: "Los Primeros Dragones (2★ al 6★)", description: "Los Primeros Dragones (2★ al 6★) arc", startEp: 48, endEp: 56 },
                { id: "nuova-eis", title: "Nuova Shenron (4★) y Eis Shenron (6★)", description: "Nuova Shenron (4★) y Eis Shenron (6★) arc", startEp: 57, endEp: 60 },
                { id: "omega-shenron", title: "Omega Shenron (1★) y el Final Eterno", description: "Omega Shenron (1★) y el Final Eterno arc", startEp: 61, endEp: 64 },
            ],
        },
    ],
    [DRAGON_BALL_SERIES.KAI]: [
        {
            id: "saiyajin",
            title: "Saga de los Saiyajin",
            description: "Saga de los Saiyajin saga",
            startEp: 1,
            endEp: 17,
            subSagas: [
                { id: "llegada-raditz", title: "La Llegada de Raditz y el Sacrificio de Goku", description: "La Llegada de Raditz y el Sacrificio de Goku arc", startEp: 1, endEp: 4 },
                { id: "entrenamiento-sayajin", title: "El Camino de la Serpiente y el Entrenamiento", description: "El Camino de la Serpiente y el Entrenamiento arc", startEp: 5, endEp: 9 },
                { id: "batalla-vegeta", title: "La Batalla Decisiva: Goku vs Vegeta", description: "La Batalla Decisiva: Goku vs Vegeta arc", startEp: 10, endEp: 17 },
            ],
        },
        {
            id: "namek-freezer",
            title: "Saga de Freezer",
            description: "Saga de Freezer saga",
            startEp: 18,
            endEp: 54,
            subSagas: [
                { id: "viaje-namek", title: "Viaje a Namekusei y las Fuerzas Especiales Ginyu", description: "Viaje a Namekusei y las Fuerzas Especiales Ginyu arc", startEp: 18, endEp: 35 },
                { id: "batalla-freezer", title: "La Batalla contra Freezer y el Super Saiyajin", description: "La Batalla contra Freezer y el Super Saiyajin arc", startEp: 36, endEp: 54 },
            ],
        },
        {
            id: "androides-cell",
            title: "Saga de los Androides y Cell",
            description: "Saga de los Androides y Cell saga",
            startEp: 55,
            endEp: 98,
            subSagas: [
                { id: "amenaza-androides", title: "La Amenaza de los Androides 17 y 18", description: "La Amenaza de los Androides 17 y 18 arc", startEp: 55, endEp: 67 },
                { id: "evolucion-cell", title: "La Evolución de Cell hacia la Perfección", description: "La Evolución de Cell hacia la Perfección arc", startEp: 68, endEp: 82 },
                { id: "juegos-cell", title: "Los Juegos de Cell y el Super Saiyajin 2 de Gohan", description: "Los Juegos de Cell y el Super Saiyajin 2 de Gohan arc", startEp: 83, endEp: 98 },
            ],
        },
        {
            id: "majin-buu",
            title: "Saga de Majin Buu",
            description: "Saga de Majin Buu saga",
            startEp: 99,
            endEp: 167,
            subSagas: [
                { id: "torneo-25-buu", title: "El 25° Torneo y el Despertar de Majin Buu", description: "El 25° Torneo y el Despertar de Majin Buu arc", startEp: 99, endEp: 114 },
                { id: "fusiones-super-buu", title: "Super Saiyajin 3, Gotenks y Vegetto", description: "Super Saiyajin 3, Gotenks y Vegetto arc", startEp: 115, endEp: 145 },
                { id: "kid-buu-final", title: "La Batalla Final contra Kid Buu y el Gran Final", description: "La Batalla Final contra Kid Buu y el Gran Final arc", startEp: 146, endEp: 167 },
            ],
        },
    ],
    [DRAGON_BALL_SERIES.SUPER]: [
        {
            id: "batalla-dioses",
            title: "Saga de la Batalla de los Dioses",
            description: "Saga de la Batalla de los Dioses saga",
            startEp: 1,
            endEp: 14,
            subSagas: [
                { id: "llegada-beerus", title: "La Profecía y la Llegada de Beerus", description: "La Profecía y la Llegada de Beerus arc", startEp: 1, endEp: 5 },
                { id: "ssg-batalla", title: "El Super Saiyajin Dios y la Batalla", description: "El Super Saiyajin Dios y la Batalla arc", startEp: 6, endEp: 14 },
            ],
        },
        {
            id: "resurreccion-f",
            title: "Saga de la Resurrección de 'F'",
            description: "Saga de la Resurrección de 'F' saga",
            startEp: 15,
            endEp: 27,
            subSagas: [
                { id: "resurreccion-preparacion", title: "La Resurrección y el Entrenamiento", description: "La Resurrección y el Entrenamiento arc", startEp: 15, endEp: 18 },
                { id: "freezer-dorado", title: "Freezer Dorado vs Goku y Vegeta", description: "Freezer Dorado vs Goku y Vegeta arc", startEp: 19, endEp: 27 },
            ],
        },
        {
            id: "universo-6",
            title: "Saga del Torneo del Universo 6",
            description: "Saga del Torneo del Universo 6 saga",
            startEp: 28,
            endEp: 41,
            subSagas: [
                { id: "torneo-u6", title: "El Torneo entre Universo 6 y 7", description: "El Torneo entre Universo 6 y 7 arc", startEp: 28, endEp: 41 },
            ],
        },
        {
            id: "copy-vegeta",
            title: "Saga del Agua Sobrenatural (Vegeta Copia)",
            description: "Saga del Agua Sobrenatural (Vegeta Copia) saga",
            startEp: 42,
            endEp: 46,
            subSagas: [
                { id: "copy-vegeta", title: "Vegeta Copia (Relleno)", description: "Vegeta Copia (Relleno) arc", startEp: 42, endEp: 46 },
            ],
        },
        {
            id: "trunks-futuro",
            title: "Saga de Goku Black",
            description: "Saga de Goku Black saga",
            startEp: 47,
            endEp: 76,
            subSagas: [
                { id: "goku-black-aparicion", title: "El Misterio de Goku Black", description: "El Misterio de Goku Black arc", startEp: 47, endEp: 61 },
                { id: "zamasu-fusion", title: "Zamasu Fusionado y el Futuro Destruido", description: "Zamasu Fusionado y el Futuro Destruido arc", startEp: 62, endEp: 76 },
            ],
        },
        {
            id: "exhibicion-zen",
            title: "Saga de Exhibición Zen",
            description: "Saga de Exhibición Zen saga",
            startEp: 77,
            endEp: 81,
            subSagas: [
                { id: "exhibicion", title: "Torneo de Exhibición de Todo", description: "Torneo de Exhibición de Todo arc", startEp: 77, endEp: 81 },
            ],
        },
        {
            id: "reclutamiento-u7",
            title: "Saga de Reclutamiento",
            description: "Saga de Reclutamiento saga",
            startEp: 82,
            endEp: 96,
            subSagas: [
                { id: "reclutamiento", title: "Reclutamiento del Equipo Universo 7", description: "Reclutamiento del Equipo Universo 7 arc", startEp: 82, endEp: 96 },
            ],
        },
        {
            id: "torneo-poder",
            title: "Saga del Torneo del Poder",
            description: "Saga del Torneo del Poder saga",
            startEp: 97,
            endEp: 131,
            subSagas: [
                { id: "torneo-poder-caos-inicial", title: "El Torneo del Poder — 80 Guerreros en el Caos", description: "El Torneo del Poder — 80 Guerreros en el Caos arc", startEp: 97, endEp: 104 },
                { id: "universos-caen-jiren-round1", title: "La Caída del Universo 6 y Goku vs Jiren (Ronda 1)", description: "La Caída del Universo 6 y Goku vs Jiren (Ronda 1) arc", startEp: 105, endEp: 111 },
                { id: "ui-signal-guerreros-u7", title: "Ultra Instinto Señal y el Equipo Universo 7", description: "Ultra Instinto Señal y el Equipo Universo 7 arc", startEp: 112, endEp: 122 },
                { id: "ultra-instinto-completo-victoria", title: "Ultra Instinto Completo y el Triunfo Final", description: "Ultra Instinto Completo y el Triunfo Final arc", startEp: 123, endEp: 131 },
            ],
        },
    ],
    [DRAGON_BALL_SERIES.DAIMA]: [
        {
            id: "daima",
            title: "Arco de Daima — El Reino Demoníaco",
            description: "Arco de Daima — El Reino Demoníaco saga",
            startEp: 1,
            endEp: 20,
            subSagas: [
                { id: "conspiracion-conversion", title: "La Conspiración — Goku se convierte en Niño", description: "La Conspiración — Goku se convierte en Niño arc", startEp: 1, endEp: 3 },
                { id: "tercer-mundo", title: "El Tercer Mundo Demoníaco y Panzy", description: "El Tercer Mundo Demoníaco y Panzy arc", startEp: 4, endEp: 7 },
                { id: "tamagami-segundo-mundo", title: "El Segundo Mundo Demoníaco y los Tamagami", description: "El Segundo Mundo Demoníaco y los Tamagami arc", startEp: 8, endEp: 14 },
                { id: "primer-mundo-gomah-final", title: "El Primer Mundo y la Batalla Final contra el Rey Gomah", description: "El Primer Mundo y la Batalla Final contra el Rey Gomah arc", startEp: 15, endEp: 20 },
            ],
        },
    ],
};

DRAGON_BALL_SAGAS[DRAGON_BALL_SERIES.KAI_FINAL_CHAPTERS] = DRAGON_BALL_SAGAS[DRAGON_BALL_SERIES.KAI];