//go:build ignore

// gen-useragents generates internal/util/user_agent_list.go from
// internal/util/data/user_agents.jsonl.
//
// Run from apps/server root:
//
//	go run ./cmd/gen-useragents/main.go
package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

type uaEntry struct {
	UserAgent string `json:"useragent"`
}

func main() {
	f, err := os.Open("internal/util/data/user_agents.jsonl")
	if err != nil {
		log.Fatalf("open: %v", err)
	}
	defer f.Close()

	var agents []string
	dec := json.NewDecoder(bufio.NewReaderSize(f, 1<<20))
	for dec.More() {
		var entry uaEntry
		if err := dec.Decode(&entry); err != nil {
			// Tolerate malformed trailing data
			log.Printf("decode warning: %v", err)
			break
		}
		if ua := strings.TrimSpace(entry.UserAgent); ua != "" {
			agents = append(agents, ua)
		}
	}

	var buf bytes.Buffer
	buf.WriteString("package util\n\n")
	buf.WriteString("// Code generated by cmd/gen-useragents. DO NOT EDIT.\n\n")
	buf.WriteString("var UserAgentList = []string{\n")
	for _, ua := range agents {
		fmt.Fprintf(&buf, "\t%q,\n", ua)
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("gofmt: %v\n---\n%s", err, buf.String())
	}

	out := "internal/util/user_agent_list.go"
	if err := os.WriteFile(out, formatted, 0o644); err != nil {
		log.Fatalf("write: %v", err)
	}
	fmt.Printf("✅ Generated %d user agents → %s\n", len(agents), out)
}
