// Dragon Ball Movie Catalog — Static Data Source

export type DbzMovie = {
    id: string
    title: string
    year: string
    image: string
    duration: string
    description: string
    saga: string // which series arc it belongs to
    streamId?: string // future: torrent/stream infohash
}

export const dbzMovies: DbzMovie[] = [
    {
        id: "movie-1",
        title: "La Leyenda del Gran Guerrero",
        year: "1989",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "50 min",
        saga: "Dragon Ball",
        description: "Goku y sus amigos deben detener a un dictador alienígena que intenta conquistar el planeta.",
    },
    {
        id: "movie-2",
        title: "Sleeping Princess in Devil's Castle",
        year: "1987",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "45 min",
        saga: "Dragon Ball",
        description: "Goku y Krilin se entrenan bajo las órdenes de Roshi y deben rescatar a una princesa misteriosa.",
    },
    {
        id: "movie-3",
        title: "Mystical Adventure",
        year: "1988",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "45 min",
        saga: "Dragon Ball",
        description: "Un emperador busca las Esferas del Dragón para encontrar a su legendario guerrero.",
    },
    {
        id: "movie-z1",
        title: "¡El hombre más fuerte del mundo!",
        year: "1990",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "45 min",
        saga: "Dragon Ball Z",
        description: "Goku enfrenta a Garlic Jr., quien desea vengarse de Kami utilizando las Esferas del Dragón.",
    },
    {
        id: "movie-z2",
        title: "El más fuerte del mundo",
        year: "1990",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "48 min",
        saga: "Dragon Ball Z",
        description: "Dr. Wheelo usa su cerebro robótico para dominar el mundo, buscando habitar el cuerpo más poderoso.",
    },
    {
        id: "movie-z3",
        title: "Los rivales más poderosos",
        year: "1991",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "48 min",
        saga: "Dragon Ball Z",
        description: "Un maestro de las artes marciales viene del espacio buscando el guerrero legendario.",
    },
    {
        id: "movie-z4",
        title: "El súper guerrero Lord Slug",
        year: "1991",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "51 min",
        saga: "Dragon Ball Z",
        description: "Un Namekiano malvado e inmortal usa las Esferas del Dragón para rejuvenecer y dominar la Tierra.",
    },
    {
        id: "movie-z5",
        title: "El combate definitivo — La victoria de Goku!",
        year: "1991",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "53 min",
        saga: "Dragon Ball Z",
        description: "Cooler, hermano mayor de Freezer, viene a vengar la derrota de su familia a manos de Goku.",
    },
    {
        id: "movie-z6",
        title: "La Galaxia en peligro",
        year: "1992",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "46 min",
        saga: "Dragon Ball Z",
        description: "Cooler regresa usando una brigada de robots metálicos para conquistar el planeta Namek.",
    },
    {
        id: "movie-z7",
        title: "Super Android 13!",
        year: "1992",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "46 min",
        saga: "Dragon Ball Z",
        description: "Los androides creados por el Dr. Gero buscan eliminar a Goku con una misión de exterminio.",
    },
    {
        id: "movie-z8",
        title: "El combate definitivo para toda la tierra",
        year: "1993",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "74 min",
        saga: "Dragon Ball Z",
        description: "Broly, el Súper Saiyajin Legendario, libera su poder destructor en un planeta perdido.",
        streamId: "broly-legendary-1993",
    },
    {
        id: "movie-z9",
        title: "El combate! Los 10.000 millones de guerreros",
        year: "1993",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "48 min",
        saga: "Dragon Ball Z",
        description: "Bojack y sus guerreros galácticos se liberan de su prisión planetaria para sembrar el caos.",
    },
    {
        id: "movie-z10",
        title: "¡El regreso de Broly!",
        year: "1994",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "51 min",
        saga: "Dragon Ball Z",
        description: "Broly regresa de entre los muertos y aterriza en la Tierra en busca de revancha.",
    },
    {
        id: "movie-z11",
        title: "El ataque del dragón",
        year: "1994",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "40 min",
        saga: "Dragon Ball Z",
        description: "Un dinosaurio mutante amenaza la Tierra y el pequeño Trunks debe enfrentarlo.",
    },
    {
        id: "movie-z12",
        title: "¡Fusión!",
        year: "1995",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "51 min",
        saga: "Dragon Ball Z",
        description: "Los guerreros del Otro Mundo amenazan al planeta Tierra con Bio-Broly.",
    },
    {
        id: "movie-z13",
        title: "El renacimiento de Fusión — ¡Goku y Vegeta!",
        year: "1995",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "51 min",
        saga: "Dragon Ball Z",
        description: "Janemba transforma el Otro Mundo y Goku debe fusionarse con Vegeta para derrotarlo.",
    },
    {
        id: "movie-z14",
        title: "El camino hacia el más poderoso",
        year: "1996",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "51 min",
        saga: "Dragon Ball Z",
        description: "Broly regresa una vez más en la tercera y última película de la trilogía del Saiyajin legendario.",
    },
    {
        id: "movie-super-bg",
        title: "Dragon Ball Super: Broly",
        year: "2018",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "100 min",
        saga: "Dragon Ball Super",
        description: "El origen canónico de Broly: un Saiyajin de poder incalculable criado en un planeta hostil y arrastrado a una batalla devastadora.",
        streamId: "dbs-broly-2018",
    },
    {
        id: "movie-super-super",
        title: "Dragon Ball Super: Super Hero",
        year: "2022",
        image: "https://image.tmdb.org/t/p/w600_and_h900_face/22ZDEBEMe0I485n3dO1fI2lmbI0.jpg",
        duration: "100 min",
        saga: "Dragon Ball Super",
        description: "El Ejército del Pasillo Rojo crea dos nuevos Androides. Piccolo y Gohan deberán despertar un poder oculto para salvar la Tierra.",
        streamId: "dbs-super-hero-2022",
    },
]
